sudo: false
language: python
services:
  - memcached
  - mysql
  - riak
  - postgresql
  - redis-server
  - cassandra
python:
  - "2.7"
cache:
  directories:
    - node_modules
    - $HOME/.cache/pip/wheels
    - "$HOME/virtualenv/python2.7.9"
env:
  matrix:
    - TEST_SUITE=acceptance
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=on
    - SENTRY_LIGHT_BUILD=1
    - SENTRY_SKIP_BACKEND_VALIDATION=1
install:
  - make travis-install-$TEST_SUITE
script:
  - make travis-lint-$TEST_SUITE
  - make travis-test-$TEST_SUITE
after_success:
  - codecov -e TEST_SUITE
